services:
  build_triedb:
    image: monad-execution-builder:latest
    command: monad-mpt --storage /monad/triedb/test.db --create --root-offsets-chunk-count=2
    volumes:
      - ./node:/monad
    privileged: true
    ulimits: &ulimits
      nofile:
        soft: 1048576
        hard: 1048576
      memlock:
        soft: 16770785280
        hard: 16770785280

  build_genesis:
    image: monad-execution-builder:latest
    depends_on:
      build_triedb:
        condition: service_completed_successfully
    volumes:
      - ./node:/monad
    privileged: true
    command:
      monad
      --chain monad_devnet
      --db /monad/triedb/test.db
      --block_db /monad/ledger
      --nblocks 0
      --log_level ERROR
    ulimits: *ulimits

  monad_execution:
    image: monad-execution-builder:latest
    depends_on:
      build_triedb:
        condition: service_completed_successfully
      build_genesis:
        condition: service_completed_successfully
    volumes:
      - ./node:/monad
    privileged: true
    command: |
      monad
      --chain monad_devnet
      --db /monad/triedb/test.db
      --block_db /monad/ledger
      --statesync /monad/statesync.sock
      --log_level ERROR
    ulimits: *ulimits

  monad_node:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${DEVNET_DIR}/Dockerfile
      args:
        GIT_TAG_VERSION: ${GIT_TAG_VERSION}
    image: monad-node:latest
    depends_on:
      - build_triedb
      - monad_execution
    environment:
      - RUST_LOG=
    volumes:
      - ./node:/monad
    privileged: true
    command: |
      monad-node
      --secp-identity /monad/config/id-secp
      --bls-identity /monad/config/id-bls
      --node-config /monad/config/node.toml
      --forkpoint-config /monad/config/forkpoint.genesis.toml
      --validators-path /monad/config/validators.toml
      --persisted-peers-path /monad/config/peers.toml
      --statesync-ipc-path /monad/statesync.sock
      --wal-path /monad/wal
      --mempool-ipc-path /monad/mempool.sock
      --control-panel-ipc-path /monad/controlpanel.sock
      --ledger-path /monad/ledger
      --triedb-path /monad/triedb
    ulimits: *ulimits

  monad_rpc:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${RPC_DIR}/Dockerfile
      args:
        GIT_TAG_VERSION: ${GIT_TAG_VERSION}
    image: monad-rpc:latest
    depends_on:
      - build_triedb
      - monad_node
    volumes:
      - ./node:/monad
    privileged: true
    ports:
      - "8080:8080"
    command: |
      monad-rpc
      --ipc-path /monad/mempool.sock
      --triedb-path /monad/triedb
      --node-config /monad/config/node.toml
    ulimits: *ulimits
